### ISSUE TITLE
Copyright removed

### ISSUE THREAD

**Issue by eldruin** [nisembedded/veml7700#1]
That driver is mostly my veml6030 driver with some modifications but you have removed the MIT license and my copyright replacing it with yours.
This is not acceptable.
Compare for example [this file](https://github.com/eldruin/veml6030-rs/blob/master/src/device_impl.rs) and [this file](https://github.com/no111u3/veml7700/blob/5dd943c19fb2d42f6c1bd0caf589717e974496f5/src/device_impl.rs)

**Comment by no111u3** [comment]
Fixed in version 0.1.5, sorry for some copyright issues.
