### ISSUE TITLE
Does not operate with embedded-hal 1.0.0-rc.1

### ISSUE THREAD

**Issue by ShakenCodes** [nisembedded/veml7700#2]
Breaking changes in embedded-hal 1.0.0-rc.1 are incompatible with this driver.

I have a working version at: https://github.com/Radiator-Labs/veml7700, which is operating on my STM32WL55 board.

I am not able to submit a PR at this time, as the examples no longer compile. This is because dev-dependency stm32f4xx-hal does not yet support the new embedded-hal; see https://github.com/stm32-rs/stm32f4xx-hal/issues/686

**Comment by no111u3** [comment]
Fixed by #3

**Comment by no111u3** [comment]
Fixed by #3
